-- Gastronomia, ex: Lays Vinagre, etc.
CREATE TABLE IF NOT EXISTS wine.pairings
(
  pairing_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  category_id BIGINT,
  pairing_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  CONSTRAINT pk_pairings PRIMARY KEY (pairing_id),
  CONSTRAINT uq_pairings_name UNIQUE (pairing_name),
  CONSTRAINT fk_pairings_category FOREIGN KEY (category_id) REFERENCES wine.pairing_categories(category_id)
);