-- Sub-regions, ex: DOC Alentejo - Portalegre
CREATE TABLE IF NOT EXISTS wine.sub_regions
(
  region_id BIGINT NOT NULL,
  sub_region_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  sub_region_name VARCHAR(255) NOT NULL,
  CONSTRAINT pk_sub_regions PRIMARY KEY (sub_region_id),
  CONSTRAINT uq_sub_regions_name UNIQUE (sub_region_name),
  CONSTRAINT fk_sub_region_region FOREIGN KEY (region_id) REFERENCES wine.regions(region_id)
);
