-- Wines
CREATE TABLE IF NOT EXISTS wine.wines
(
  wine_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  brand VARCHAR(255) NOT NULL,
  producer_id BIGINT,
  wine_type wine.wine_type,
  vintage INT,

  -- Location
  appellation_id BIGINT,
  region_id BIGINT,
  sub_region_id BIGINT,

  -- Terroir
  climate TEXT,

  -- Tasting Notes
  aspect TEXT,
  aroma TEXT,
  flavour TEXT,

  -- Technical
  alcohol_by_volume_percentage NUMERIC(4,2),
  total_acidity_g_l NUMERIC(5,2),
  volatile_acidity_g_l NUMERIC(5,2),
  residual_sugar_g_l NUMERIC(5,2),
  ph NUMERIC(3,2),
 
  -- Serving
  service_temperature_min_celsius INT,
  service_temperature_max_celsius INT,
  allergens VARCHAR(255),
  volume_ml INT,

  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,


  -- Constraints
  CONSTRAINT pk_wines PRIMARY KEY (wine_id),
  CONSTRAINT fk_wines_producer FOREIGN KEY (producer_id) REFERENCES wine.producers(producer_id),
  CONSTRAINT fk_wines_appellation FOREIGN KEY (appellation_id) REFERENCES wine.appellations(appellation_id),
  CONSTRAINT fk_wines_region FOREIGN KEY (region_id) REFERENCES wine.regions(region_id),
  CONSTRAINT fk_wines_sub_region FOREIGN KEY (sub_region_id) REFERENCES wine.sub_regions(sub_region_id),

  CONSTRAINT chk_wines_vintage CHECK (vintage IS NULL OR (vintage > 1800 AND vintage <= EXTRACT(YEAR FROM CURRENT_DATE))),
  CONSTRAINT chk_wines_alcohol CHECK (alcohol_by_volume_percentage IS NULL OR (alcohol_by_volume_percentage >= 5 AND alcohol_by_volume_percentage <= 25)),
  CONSTRAINT chk_wines_ph CHECK (ph IS NULL OR (ph >= 2.5 AND ph <= 4.5)),
  CONSTRAINT chk_wines_acidity CHECK (total_acidity_g_l IS NULL OR total_acidity_g_l >= 0),
  CONSTRAINT chk_wines_volatile_acidity CHECK (volatile_acidity_g_l IS NULL OR volatile_acidity_g_l >= 0),
  CONSTRAINT chk_wines_sugar CHECK (residual_sugar_g_l IS NULL OR residual_sugar_g_l >= 0),
  CONSTRAINT chk_wines_volume CHECK (volume_ml IS NULL OR volume_ml > 0),
  CONSTRAINT chk_wines_service_temp CHECK (service_temperature_min_celsius IS NULL OR service_temperature_max_celsius IS NULL OR (service_temperature_min_celsius <= service_temperature_max_celsius))
);
