-- Appellations, ex: Regional, DOC, Vinho de Portugal, Vinho da UE
CREATE TABLE IF NOT EXISTS wine.appellations
(
  appellation_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  appellation_name VARCHAR(255) NOT NULL,
  CONSTRAINT pk_appellations PRIMARY KEY (appellation_id),
  CONSTRAINT uq_appellations_name UNIQUE (appellation_name)
);