-- Distribuidores de vinhos, ex: Decante Vinhos
CREATE TABLE IF NOT EXISTS wine.distributors
(
  distributor_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  distributor_name VARCHAR(255) NOT NULL,
  distributor_website_url VARCHAR(2048),
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  CONSTRAINT pk_distributor PRIMARY KEY (distributor_id),
  CONSTRAINT uq_distributor_name UNIQUE (distributor_name)
);
