-- Grapes/Varieties, ex: Touriga Nacional, Alvarinho, etc.
CREATE TABLE IF NOT EXISTS wine.grapes
(
  grape_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  grape_name VARCHAR(255) NOT NULL,
  grape_color VARCHAR(255),
  grape_species VARCHAR(255),
  grape_origin VARCHAR(255),
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  CONSTRAINT pk_grapes PRIMARY KEY (grape_id),
  CONSTRAINT uq_grapes_name UNIQUE (grape_name)
);
