-- Pairing Categories, ex: Carnes, Peixe, etc.
CREATE TABLE IF NOT EXISTS wine.pairing_categories
(
  category_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  category_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  CONSTRAINT pk_pairing_categories PRIMARY KEY (category_id),
  CONSTRAINT uq_pairing_categories_name UNIQUE (category_name)
);
