-- Producer, ex: Casa Ferreirinha
CREATE TABLE IF NOT EXISTS wine.producers
(
  producer_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  producer_name VARCHAR(255) NOT NULL,
  producer_website_url VARCHAR(255),
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  CONSTRAINT pk_producers PRIMARY KEY (producer_id),
  CONSTRAINT uq_producers_name UNIQUE (producer_name)
);
