-- Regiões, ex: Alentejo, Douro, etc.
CREATE TABLE IF NOT EXISTS wine.regions
(
  region_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  region_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  CONSTRAINT pk_regions PRIMARY KEY (region_id),
  CONSTRAINT uq_regions_name UNIQUE (region_name)
);
