-- Os  solos onde a/as vinhas estão plantadas,
-- ex: Granítico, Xistoso, Franco-argiloso, etc.
CREATE TABLE IF NOT EXISTS wine.soils
(
  soil_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  soil_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  CONSTRAINT pk_soils PRIMARY KEY (soil_id),
  CONSTRAINT uq_soils_name UNIQUE (soil_name)
);
