-- Fontes de informação (Websites, etc.)
-- Essencial para a confiança do utilizador.
CREATE TABLE IF NOT EXISTS wine.sources
(
  source_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source_name VARCHAR(255) NOT NULL,
  source_category VARCHAR(255),  
  source_website_url VARCHAR(2048),
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  CONSTRAINT pk_sources PRIMARY KEY (source_id)
);
