-- Vendedores / Pontos de Venda, ex: Lojas Online, etc
CREATE TABLE IF NOT EXISTS wine.vendors (
    vendor_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    vendor_name VARCHAR(255) NOT NULL,
    vendor_type VARCHAR(255),
    website_url VARCHAR(2048),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_vendors PRIMARY KEY (vendor_id),
    CONSTRAINT uq_vendors_name UNIQUE (vendor_name)
);
