-- Winemakers, ex: Paulo Laureano
CREATE TABLE IF NOT EXISTS wine.winemakers
(
  winemaker_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  winemaker_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  CONSTRAINT pk_winemakers PRIMARY KEY (winemaker_id),
  CONSTRAINT uq_winemakers_name UNIQUE (winemaker_name)  
);
